apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: app-secrets
  namespace: default
spec:
  encryptedData:
    api-key: AgBBYkOOmEAs1GcYTy4SFK6LUS475ta2FmbCU03SHj/0CJ/tzMjfip4WttpaTOpXfERobt1oV9Qjq8JdnLW5ckiRdbVkYMWU6Qw6FSykuzgv/shye7YIMjzmjduScu9kf26HuGiErTa/CaTMoVVUNpAm3dhvKLC2gRqgpvW6RLHGGX3IOA01cbQPoFOtjucrosluzio1gRcr2Zmkv3T34XI573TWXlPZ7wMtRyztwK1a2LIVd6Rl+2ynRgpmGqH6H5ow8idiE5aAHVsMWaFII4lqkBnjZSctKWQQkuSpyqeqv7OSUut8oKlU8tb/S9S+U/+kxhJ3JOpVoCr1r4Cu/DdGYp9WcdNRxO2kceN0d00jhc1H1MbkN1ES8DXjMkt1SNFUSZ86fDQO0YbYzpaiqAOEYwvCGva3msl4/SXt7gEXOz2oSRLvat9KwJZ4uXjcO+ofBHCMr0yFviWz38h97ydX4M/X5EUPKCZD6ZCFISE20S9pY5+EA+isRXNR/lk8KTarn/ZNLS7W3msjBUw1FSf/9P3kMIuxWTGdh/eO0Iypqfp26dBLPcLcxtH7Tjdj7H2dm5epqxJza9/8CDNxxwpssJN/a27VqOa4MFanl0NERCW5dQZZ1teUgJIF1aduQZN/QZQLvfwX2x0W6usc1tSuMsXSG/wBUqn5hjhreI+hyfssnneTsOJTf8IB1TPGLIDrP6/mv8lWVGU=
    db-password: AgBaAC+VrQ1I1T8eH/0Jpe+Fxtlnym6KGMsFxPJ3C5xV7RXFpWOKxldV1hG/7lzeMlKEP639/yslcJOZkFhLjfbts0YZ+J0jDxV35zCaw47qBe9dnW7TT565+7KAoj2JHmpdtCLZYBHxAH+lGNVETBbg7Fc6ab36rthiCDgLxIzMTzDXZmwYJeB7wg7VOdUFnfgoXyU5KOrePojD5kWAo0+AwGCV/RyjOTYxAQ/WVo3HYVcskAsicho0KGu2B/SuygcS+zEMpe88IQhTb8+4RcmQsKN9rGUEVATDDwWF5bSJTINrWFHCtU+QyCv5eBYmVMu/qo1cikNlmCu11ZWwHXLYH9gg6x/IAi2I8rF7E/SZt3M5k8JUfjyx8I7qenHqwO0sDog7iTYHAX+vrPGZvTwTguWzFRD+M/4OJA/BYEIZFOKuPHcYQ9X3xvo2HL6PWT2HumOq8fNlLtpv+CON5C/SoZn7LNaD2HTiL6sFQQK4mvqp6nq6GAl8/boCOZHizYlQS/ylc6E5dulfxkbd1vD0t+VoGc9XRH2Y3bSbO7E2Sdrv8q0zjWq4zmxA7CS6nWa3Xdstee99dhTLrTuwen9TkEMytLiFm4qzAIMqSiE2x845vYBkPpE9wBm++i9qCKmgWbsHYGIlqwFZtMATxyRxw3EfmrkeMOjF2LtCP35o1/KP2G43DB/el3LQ7HWCxLQBU+hrS6NVxpL6ViQ85A==
  template:
    metadata:
      creationTimestamp: null
      name: app-secrets
      namespace: default
---
