apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: app-secrets
  namespace: default
spec:
  encryptedData:
    api-key: AgAFCwaiFc7FtvoPQATcT7ROJAeNrfdkGeSXrs3ehMi7dYKZ6nw1tHilNMOB46JgRa6xwXppXc7DyV96cPZc3+DDyvERJhD4ijj0wGHdcZt54dCWf0gUjM+OpP+ynkbpC9rAkhFliFIa0/gh4UERU8Eq1aBbdXpJTYqmhlZm/VRTvYEnjWxVeXR8QvTPfokUemG/UT5nDHmvCXtu+xLRiV09bUytey8kE1uAD9sP1eSC9LiJ3Sh83lZmy15XGaYPcDqcrC2O6/PPWK/c/IftxY/v1CbfXXOQG2Jk+Nl8zayPx2NnGyHI+k726s9wLyl30OJJ0yEMSF9xY7k8qNUJ2cedJpsgt12MfHOxYR40ilefIyzxw6krAdL73824maKS8FA3PoIUBwK+NGpWKLiJqpGyITK1VfEtPTZoXP8e6KNv83WEYwc/1P4jlB0Y1dLYWgBr7pOwzy/P1EdC7e9cNh8mPmSSr8ti8DfriAbtQW8gGMQ+uw/JYNbt8RGTegrqBCQqNrkS5I5OgLp0Drk5nsJkc1ocoF8mBW26wbCeF1ljhllBfr01tjKwU4i43saT88dj9zXpG9FdcaCAQHc5KTyGz8XHEVa/qxF7cT3d+yuK3XEDA/1cUNKeT7XD/GoXTpIbfvHkzZuI1ddWEExuIRkJe51XP03Yn6/6mgYAqGjEmfk/xS7D41IQS1Q0K32l7VBJvXu6hi/PKiU6Mw==
    db-password: AgBl/x8irnigWILgGYf6pfOnMm55H1aXS+P+co3FpOwy656Boj4s4jQz075Q87X5PDN0dvgVTIKp6F4ZqnQ9vUffCYnR1wXAuoRc74cvg61+fa2y523y/oMJkOLQqu7B78jR7scRG1g1DIeKBRzrCqRjx9PoxaJpROdDzpUF8eGx+ctHwVCHnJiiNvYBHI1hbtjIJq+SqX2SAMB+TRLPfp0OQOvCFN5pkE/bSs18Tcjf3gUfqQ/Sym+bMJnRsz2aR+ZeStzeGEyaUuOyA2TfsDpZyekaGSr3Lrr6x5v94fwp8f0IqqAq1hrQwBXfFtc9Da5r9sWQUk4/WG4lUnLHG9A+pmCCYB7lZ3DlsC4skimKcKGwkgEiNqkV0Cj03CYVVZ4aSnaAtLltqW3mOpCwdlY7olYdnb6ocRbudPwFarGcw6LL7tmAPj84EbtNMPfXUb+FtciAYVYH2eP3cIkNNIV4UaGgWTMpfWAPTS8fg4nJnqNmqzT/R8RR96u05RsEX6NN775ULO8tWJ1BaIpNpEGL+Y1jDNLqA1Y/8ZzrW9xkySWYBGtnNgeHlcWNoqYkP+paJMRgJ8hYaDjBmMzFtAycionRscw9Ny+jJgbdnp7kLy/AD13XvwrtZ4DpqbFYjKAHo+yIQoSUtBdL8I2LCbs3gU0JFnw2ZkulggY7YJ/F06DIOMahRA4qoTP+lgieepMXRb/079UOi17x+c8EBA==
  template:
    metadata:
      creationTimestamp: null
      name: app-secrets
      namespace: default
---
